PACKAGE = visualSensorNet

SOURCE  = \
		Environnement.java \
		JTextPanel.java \
        Mouseclick.java \
		Placer.java \
        Plan.java \
        SensorSim.java \
        SensorSimple.java \
        Sink.java \
        Target.java \



RMI_SOURCE  =

MAIN        =

include $(J_SIM)/Makefile