PACKAGE = drcl.inet.mac

SOURCE  = \
    DeferSensorTimer.java \
    Mac_CSMA \
    Mac_Sensor_Packet \
    Mac_Sensor_Timer \
    MacSensor_DeferSensorTimer \
    MacSensor_RxSensorTimer \
    MacSensor TxSensorTimer \
    RxSensorTimer \
    TxSensorTimer \

RMI_SOURCE  =

MAIN        =

include $(J_SIM)/Makefile
