PACKAGE = drcl.inet.sensorsim.LEACH

SOURCE  = \
		LEACH_CH_Packet.java \
        LEACH_Data_Packet.java \
        LEACH_Join_Packet.java \
        LEACH_SCH_Packet.java \
        LEACHApp.java \
        SinkAppLEACH.java \
        WirelessLEACHAgent.java \
        LEACHAppMacSensorContract.java \

RMI_SOURCE  =

MAIN        = 

include $(J_SIM)/Makefile
