PACKAGE = drcl.inet.sensorsim

SOURCE  = \
		AcousticChannel.java \
		AcousticProp.java \
		BatteryBase.java \
		BatteryCoinCell.java \
		BatteryContract.java \
		BatteryLiNR.java \
		BatterySimple.java \
		BatteryTable.java \
		CPUAvr.java \
		CPUBase.java \
		RadioBase.java \
		RadioSimple.java \
		SeismicProp.java \
		SensorAgent.java \
		SensorAgentPhyContract.java \
		SensorApp.java \
		SensorAppAgentContract.java \
		SensorAppWirelessAgentContract.java \
		SensorChannel.java \
		SensorLocationInformation.java \
		SensorMobilityModel.java \
		SensorNeighborQueryContract.java \
		SensorNodeChannelContract.java \
		SensorNodePositionTracker.java \
		SensorPacket.java \
		SensorPhy.java \
		SensorPositionReportContract.java \
		SensorRadioPropagationModel.java \
		SensorRadioPropagationQueryContract.java \
		TargetAgent.java \
		TargetPacket.java \
		WirelessAgent.java \
		SensorLocApp.java \
		ProbePacket.java

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
