PACKAGE = drcl.inet.sensorsim

SOURCE  = \
        AcousticChannel.java \
        AcousticProp.java \
		AliveSensors.java \
		BatteryBase.java \
		BatteryContract.java \
		CPUAvr.java \
		CPUBase.java \
		SeismicProp.java \
		SensorAgent.java \
		SensorAgentPhyContract.java \
		SensorApp.java \
		SensorAppAgentContract.java \
		SensorAppWirelessAgentContract.java \
		SensorChannel.java \
        SensorLocationInformation.java \
		SensorMobilityModel.java \
		SensorNeighborQueryContract.java \
		SensorNodeChannelContract.java \
		SensorNodePositionTracker.java \
		SensorPacket.java \
		SensorPhy.java \
		SensorPositionReportContract.java \
		SensorRadioPropagationModel.java \
		SensorRadioPropagationQueryContract.java \
		TargetAgent.java \
		TargetPacket.java \
		WirelessAgent.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
