PACKAGE = drcl.inet.sensorsim.MultiHop

SOURCE  = \
		MH_Packet.java \
		MultiHopApp.java \
        NeighborQueryContract.java \
		SinkAppMH.java \



RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile