PACKAGE = drcl.inet.sensorsim.diffusion

SOURCE  = \
		ActiveTasksEntry.java \
		Attribute.java \
		AttributeVector.java \
		DataCacheEntry.java \
		DataPacket.java \
		DiffApp.java \
		DiffTimer.java \
		GradientEntry.java \
		InterestCacheEntry.java \
		InterestPacket.java \
		NegativeReinforcementPacket.java \
		PositiveReinforcementPacket.java \
		WirelessDiffAgent.java \

RMI_SOURCE  = 

MAIN        = 

include $(J_SIM)/Makefile
